name: deployment workflow
on:
  push:
    branches: [main]
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd cmsc389T-web-template
            git pull
            mkdir /pub/cyl/cmsc389T-web-template
            unalias cp
            cp -R css js assets index.html /pub/cyl/cmsc389T-web-template
            ls -l /pub/cyl/cmsc389T-web-template

